# with alias as models as attribute = TRUE
quarkus.openapi-generator.codegen.spec.with_generate_alias_as_models_yaml.generate-alias-as-models=true


# with alias as models as attribute = FALSE
quarkus.openapi-generator.codegen.spec.no_generate_alias_as_models_yaml.generate-alias-as-models=false

quarkus.keycloak.devservices.enabled=false


